FROM python:3.7
FROM postgres:latest
FROM mwendler/wget:latest

RUN manager

ADD . /manager

ENV POSTGRES_USER docker
ENV POSTGRES_PASSWORD docker
ENV POSTGRES_DB docker
ENV CSV_FILENAME data.csv


RUN wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -P /
RUN chmod +x /wait-for-it.sh
ENTRYPOINT ["/wait-for-it.sh", "db:5432", "--"]


#CMD ["python","__init__.py","__main__.py","config.py","test_integration.py","utils_postgres.py"]

CMD ["python -m manager"]