version: "3"

services:

  manager:
    build:
      context: ./dockerfile
      dockerfile: "Dockerfile.txt"
    image: "manager:latest"

    ports: 
      - "8000:8000"
    depends_on: 
      - "db"
    environment: 
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=nico
      - POSTGRES_DB=db
      - CSV_FILENAME="data.csv"
  
  db:
    image: postgres:latest
    environment: 
      - POSTGRES_PASSWORD=msecretotdepasse
      - POSTGRES_USER=nico